"""Unit tests for PortraitGenerator."""

import os
import pytest
from pathlib import Path
from PIL import Image
import tempfile
import shutil

from portrait_generator.core.generator import PortraitGenerator
from portrait_generator.core.overlay import TitleOverlayEngine
from portrait_generator.core.evaluator import QualityEvaluator
from portrait_generator.core.researcher import BiographicalResearcher
from portrait_generator.utils.gemini_client import GeminiImageClient
from portrait_generator.api.models import SubjectData, EvaluationResult, PortraitResult

# Sentinel for tests that require a real Gemini API key.
# Gemini keys are 39-char strings starting with "AIzaSy"; skip if absent or wrong format.
_api_key = os.getenv("GOOGLE_API_KEY", "")
_NO_API_KEY = not _api_key or not _api_key.startswith("AIzaSy")
_SKIP_NO_KEY = pytest.mark.skipif(_NO_API_KEY, reason="Requires real Gemini API access - set GOOGLE_API_KEY (AIzaSy... format)")


@pytest.fixture
def temp_output_dir():
    """Create temporary output directory."""
    temp_dir = tempfile.mkdtemp()
    yield Path(temp_dir)
    shutil.rmtree(temp_dir)


@pytest.fixture
def gemini_client():
    """Create a real Gemini client with test API key."""
    return GeminiImageClient(api_key="test_api_key_1234567890")


@pytest.fixture
def researcher(gemini_client):
    """Create a real researcher instance."""
    return BiographicalResearcher(gemini_client)


@pytest.fixture
def overlay_engine():
    """Create a real overlay engine instance."""
    return TitleOverlayEngine()


@pytest.fixture
def evaluator():
    """Create a real evaluator instance."""
    return QualityEvaluator()


@pytest.fixture
def generator(gemini_client, researcher, overlay_engine, evaluator, temp_output_dir):
    """Create PortraitGenerator instance with real components."""
    return PortraitGenerator(
        gemini_client=gemini_client,
        researcher=researcher,
        overlay_engine=overlay_engine,
        evaluator=evaluator,
        output_dir=temp_output_dir,
    )


class TestPortraitGeneratorInit:
    """Tests for PortraitGenerator initialization."""

    def test_init_creates_output_dir(
        self,
        gemini_client,
        researcher,
        overlay_engine,
        evaluator,
        temp_output_dir,
    ):
        """Test that initialization creates output directory."""
        output_dir = temp_output_dir / "portraits"

        generator = PortraitGenerator(
            gemini_client=gemini_client,
            researcher=researcher,
            overlay_engine=overlay_engine,
            evaluator=evaluator,
            output_dir=output_dir,
        )

        assert output_dir.exists()
        assert generator.output_dir == output_dir

    def test_init_assigns_components(self, generator, gemini_client):
        """Test that components are assigned correctly."""
        assert generator.gemini_client is gemini_client
        assert generator.researcher is not None
        assert generator.overlay_engine is not None
        assert generator.evaluator is not None


class TestGeneratePortrait:
    """Tests for generate_portrait method - validation only."""

    def test_generate_portrait_empty_name(self, generator):
        """Test error handling for empty name."""
        with pytest.raises(ValueError, match="cannot be empty"):
            generator.generate_portrait("")

    def test_generate_portrait_whitespace_name(self, generator):
        """Test error handling for whitespace-only name."""
        with pytest.raises(ValueError, match="cannot be empty"):
            generator.generate_portrait("   ")

    def test_generate_portrait_invalid_style(self, generator):
        """Test error handling for invalid style."""
        with pytest.raises(ValueError, match="Invalid styles"):
            generator.generate_portrait("Test", styles=["Invalid"])

    @_SKIP_NO_KEY
    def test_generate_portrait_success(self, tmp_path) -> None:
        """Test successful portrait generation (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_portrait_all_styles(self, tmp_path) -> None:
        """Test that all 4 styles are generated by default (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_portrait_specific_styles(self, tmp_path) -> None:
        """Test generating specific styles only (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_portrait_creates_files(self, tmp_path) -> None:
        """Test that portrait files are created (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_portrait_creates_prompts(self, tmp_path) -> None:
        """Test that prompt files are created (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_portrait_includes_metadata(self, tmp_path) -> None:
        """Test that result includes subject metadata (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_portrait_includes_evaluation(self, tmp_path) -> None:
        """Test that result includes evaluation results (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_portrait_tracks_time(self, tmp_path) -> None:
        """Test that generation time is tracked (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_portrait_force_regenerate(self, tmp_path) -> None:
        """Test force regeneration overwrites existing files (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_portrait_researcher_failure(self, tmp_path) -> None:
        """Test handling of researcher failure (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_portrait_image_generation_failure(self, tmp_path) -> None:
        """Test handling of image generation failure (requires real API)."""
        pass


class TestGenerateVersion:
    """Tests for _generate_version private method."""

    @_SKIP_NO_KEY
    def test_generate_version_creates_files(self, tmp_path) -> None:
        """Test that _generate_version creates files (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_version_bw_transformation(self, tmp_path) -> None:
        """Test that BW style applies transformation (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_version_sepia_transformation(self, tmp_path) -> None:
        """Test that Sepia style applies transformation (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_version_skips_existing(self, tmp_path) -> None:
        """Test that existing files are skipped (requires real API)."""
        pass


class TestCreatePrompt:
    """Tests for _create_prompt method."""

    def test_create_prompt_includes_name(self, generator):
        """Test that prompt includes subject name."""
        subject_data = SubjectData(
            name="Albert Einstein",
            birth_year=1879,
            death_year=1955,
            era="20th Century",
        )

        prompt = generator._create_prompt(subject_data, "Color")

        assert "Albert Einstein" in prompt

    def test_create_prompt_includes_era(self, generator):
        """Test that prompt includes era."""
        subject_data = SubjectData(
            name="Test",
            birth_year=1900,
            death_year=1950,
            era="Medieval",
        )

        prompt = generator._create_prompt(subject_data, "Color")

        assert "Medieval" in prompt

    def test_create_prompt_different_styles(self, generator):
        """Test that prompts differ by style."""
        subject_data = SubjectData(
            name="Test",
            birth_year=1900,
            death_year=1950,
            era="Modern",
        )

        prompt_bw = generator._create_prompt(subject_data, "BW")
        prompt_sepia = generator._create_prompt(subject_data, "Sepia")

        assert prompt_bw != prompt_sepia
        assert "black and white" in prompt_bw.lower()
        assert "sepia" in prompt_sepia.lower()

    def test_create_prompt_includes_quality_requirements(self, generator):
        """Test that prompt includes quality requirements."""
        subject_data = SubjectData(
            name="Test",
            birth_year=1900,
            death_year=1950,
            era="Modern",
        )

        prompt = generator._create_prompt(subject_data, "Color")

        assert "quality" in prompt.lower() or "publication" in prompt.lower()


class TestGetStyleInstructions:
    """Tests for _get_style_instructions method."""

    def test_get_style_instructions_bw(self, generator):
        """Test BW style instructions."""
        instructions = generator._get_style_instructions("BW")

        assert "black and white" in instructions.lower()

    def test_get_style_instructions_sepia(self, generator):
        """Test Sepia style instructions."""
        instructions = generator._get_style_instructions("Sepia")

        assert "sepia" in instructions.lower()

    def test_get_style_instructions_color(self, generator):
        """Test Color style instructions."""
        instructions = generator._get_style_instructions("Color")

        assert "color" in instructions.lower()

    def test_get_style_instructions_painting(self, generator):
        """Test Painting style instructions."""
        instructions = generator._get_style_instructions("Painting")

        assert "painting" in instructions.lower()

    def test_get_style_instructions_unknown(self, generator):
        """Test unknown style returns default."""
        instructions = generator._get_style_instructions("Unknown")

        assert len(instructions) > 0


class TestApplyStyleTransformation:
    """Tests for _apply_style_transformation method."""

    def test_apply_style_transformation_bw(self, generator):
        """Test BW transformation."""
        image = Image.new("RGB", (100, 100), color=(255, 0, 0))

        result = generator._apply_style_transformation(image, "BW")

        # Check that result is grayscale
        pixels = list(result.getdata())
        r, g, b = pixels[0]
        assert r == g == b

    def test_apply_style_transformation_sepia(self, generator):
        """Test Sepia transformation."""
        image = Image.new("RGB", (100, 100), color=(255, 0, 0))

        result = generator._apply_style_transformation(image, "Sepia")

        # Check that result has warm tones
        pixels = list(result.getdata())
        r, g, b = pixels[0]
        assert r >= g >= b

    def test_apply_style_transformation_color(self, generator):
        """Test Color transformation is a no-op."""
        image = Image.new("RGB", (100, 100), color=(255, 0, 0))

        result = generator._apply_style_transformation(image, "Color")

        # Should be unchanged
        assert result.getpixel((0, 0)) == (255, 0, 0)

    def test_apply_style_transformation_painting(self, generator):
        """Test Painting transformation is a no-op."""
        image = Image.new("RGB", (100, 100), color=(255, 0, 0))

        result = generator._apply_style_transformation(image, "Painting")

        # Should be unchanged
        assert result.getpixel((0, 0)) == (255, 0, 0)


class TestCreateFilename:
    """Tests for _create_filename method."""

    def test_create_filename_simple(self, generator):
        """Test filename creation for simple name."""
        filename = generator._create_filename("Albert Einstein", "BW")

        assert filename == "AlbertEinstein_BW"

    def test_create_filename_removes_spaces(self, generator):
        """Test that spaces are removed."""
        filename = generator._create_filename("John von Neumann", "Color")

        assert " " not in filename

    def test_create_filename_capitalizes(self, generator):
        """Test that name parts are capitalized."""
        filename = generator._create_filename("alan turing", "Sepia")

        assert "Alan" in filename
        assert "Turing" in filename

    def test_create_filename_different_styles(self, generator):
        """Test filename differs by style."""
        filename_bw = generator._create_filename("Test", "BW")
        filename_color = generator._create_filename("Test", "Color")

        assert filename_bw != filename_color
        assert "_BW" in filename_bw
        assert "_Color" in filename_color

    def test_create_filename_removes_special_chars(self, generator):
        """Test that special characters are removed."""
        filename = generator._create_filename("Name (test) [2024]", "BW")

        assert "(" not in filename
        assert "[" not in filename


class TestCheckExistingPortraits:
    """Tests for check_existing_portraits method."""

    def test_check_existing_portraits_none_exist(self, generator):
        """Test checking when no portraits exist."""
        results = generator.check_existing_portraits("Nonexistent Person XYZ")

        assert all(not exists for exists in results.values())

    @_SKIP_NO_KEY
    def test_check_existing_portraits_some_exist(self, tmp_path) -> None:
        """Test checking when some portraits exist (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_check_existing_portraits_all_exist(self, tmp_path) -> None:
        """Test checking when all portraits exist (requires real API)."""
        pass


class TestGenerateBatch:
    """Tests for generate_batch method."""

    def test_generate_batch_empty_list(self, generator):
        """Test error handling for empty list."""
        with pytest.raises(ValueError, match="cannot be empty"):
            generator.generate_batch([])

    @_SKIP_NO_KEY
    def test_generate_batch_success(self, tmp_path) -> None:
        """Test successful batch generation (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_batch_with_styles(self, tmp_path) -> None:
        """Test batch generation with specific styles (requires real API)."""
        pass

    @_SKIP_NO_KEY
    def test_generate_batch_handles_failures(self, tmp_path) -> None:
        """Test that batch continues after individual failures (requires real API)."""
        pass


class TestIntegration:
    """Integration tests for PortraitGenerator."""

    @_SKIP_NO_KEY
    def test_full_generation_workflow(self, tmp_path) -> None:
        """Test complete generation workflow (requires real API)."""
        pass
