"""Unit tests for PortraitGenerator."""

import pytest
from pathlib import Path
from unittest.mock import Mock, MagicMock, patch
from PIL import Image
import tempfile
import shutil

from portrait_generator.core.generator import PortraitGenerator
from portrait_generator.api.models import SubjectData, EvaluationResult, PortraitResult


@pytest.fixture
def temp_output_dir():
    """Create temporary output directory."""
    temp_dir = tempfile.mkdtemp()
    yield Path(temp_dir)
    shutil.rmtree(temp_dir)


@pytest.fixture
def mock_gemini_client():
    """Create mock Gemini client."""
    client = Mock()
    client.api_key = "test_key_1234567890"

    # Mock image generation
    def generate_image_side_effect(**kwargs):
        return Image.new("RGB", (768, 1024), color=(120, 100, 90))

    client.generate_image = Mock(side_effect=generate_image_side_effect)

    return client


@pytest.fixture
def mock_researcher():
    """Create mock researcher."""
    researcher = Mock()

    def research_side_effect(name):
        return SubjectData(
            name=name,
            birth_year=1879,
            death_year=1955,
            era="20th Century",
            appearance_notes=["Wild hair", "Mustache"],
            historical_context="Physicist",
            reference_sources=["Records"],
        )

    researcher.research_subject = Mock(side_effect=research_side_effect)

    def get_context_side_effect(subject_data):
        return {
            "name": subject_data.name,
            "era": subject_data.era,
            "birth_year": subject_data.birth_year,
            "death_year": subject_data.death_year or "Present",
            "years": subject_data.formatted_years,
            "appearance": ", ".join(subject_data.appearance_notes) if subject_data.appearance_notes else "",
            "context": subject_data.historical_context if hasattr(subject_data, 'historical_context') else "",
        }

    researcher.get_prompt_context = Mock(side_effect=get_context_side_effect)

    return researcher


@pytest.fixture
def mock_overlay_engine():
    """Create mock overlay engine."""
    engine = Mock()

    def add_overlay_side_effect(image, **kwargs):
        return image

    engine.add_overlay = Mock(side_effect=add_overlay_side_effect)

    return engine


@pytest.fixture
def mock_evaluator():
    """Create mock evaluator."""
    evaluator = Mock()

    def evaluate_side_effect(image, subject_data, style, **kwargs):
        return EvaluationResult(
            passed=True,
            scores={
                "technical": 1.0,
                "visual_quality": 0.9,
                "style_adherence": 0.85,
                "historical_accuracy": 0.9,
            },
            feedback=["All checks passed"],
            issues=[],
            recommendations=[],
        )

    evaluator.evaluate_portrait = Mock(side_effect=evaluate_side_effect)

    return evaluator


@pytest.fixture
def generator(
    mock_gemini_client,
    mock_researcher,
    mock_overlay_engine,
    mock_evaluator,
    temp_output_dir,
):
    """Create PortraitGenerator instance."""
    return PortraitGenerator(
        gemini_client=mock_gemini_client,
        researcher=mock_researcher,
        overlay_engine=mock_overlay_engine,
        evaluator=mock_evaluator,
        output_dir=temp_output_dir,
    )


class TestPortraitGeneratorInit:
    """Tests for PortraitGenerator initialization."""

    def test_init_creates_output_dir(
        self,
        mock_gemini_client,
        mock_researcher,
        mock_overlay_engine,
        mock_evaluator,
        temp_output_dir,
    ):
        """Test that initialization creates output directory."""
        output_dir = temp_output_dir / "portraits"

        generator = PortraitGenerator(
            gemini_client=mock_gemini_client,
            researcher=mock_researcher,
            overlay_engine=mock_overlay_engine,
            evaluator=mock_evaluator,
            output_dir=output_dir,
        )

        assert output_dir.exists()
        assert generator.output_dir == output_dir

    def test_init_assigns_components(self, generator, mock_gemini_client):
        """Test that components are assigned correctly."""
        assert generator.gemini_client == mock_gemini_client
        assert generator.researcher is not None
        assert generator.overlay_engine is not None
        assert generator.evaluator is not None


class TestGeneratePortrait:
    """Tests for generate_portrait method."""

    def test_generate_portrait_success(self, generator):
        """Test successful portrait generation."""
        result = generator.generate_portrait("Albert Einstein")

        assert isinstance(result, PortraitResult)
        assert result.success is True
        assert result.subject == "Albert Einstein"
        assert len(result.files) > 0

    def test_generate_portrait_all_styles(self, generator):
        """Test that all 4 styles are generated by default."""
        result = generator.generate_portrait("Test Person")

        assert len(result.files) == 4
        assert "BW" in result.files
        assert "Sepia" in result.files
        assert "Color" in result.files
        assert "Painting" in result.files

    def test_generate_portrait_specific_styles(self, generator):
        """Test generating specific styles only."""
        result = generator.generate_portrait(
            "Test Person", styles=["BW", "Color"]
        )

        assert len(result.files) == 2
        assert "BW" in result.files
        assert "Color" in result.files
        assert "Sepia" not in result.files
        assert "Painting" not in result.files

    def test_generate_portrait_creates_files(self, generator, temp_output_dir):
        """Test that portrait files are created."""
        result = generator.generate_portrait("Test Person")

        # Check that files exist
        for file_path in result.files.values():
            assert Path(file_path).exists()

    def test_generate_portrait_creates_prompts(self, generator, temp_output_dir):
        """Test that prompt files are created."""
        result = generator.generate_portrait("Test Person")

        # Check that prompt files exist
        for prompt_path in result.prompts.values():
            assert Path(prompt_path).exists()
            # Check that prompt has content
            content = Path(prompt_path).read_text()
            assert len(content) > 0
            assert "Test Person" in content

    def test_generate_portrait_empty_name(self, generator):
        """Test error handling for empty name."""
        with pytest.raises(ValueError, match="cannot be empty"):
            generator.generate_portrait("")

    def test_generate_portrait_whitespace_name(self, generator):
        """Test error handling for whitespace-only name."""
        with pytest.raises(ValueError, match="cannot be empty"):
            generator.generate_portrait("   ")

    def test_generate_portrait_invalid_style(self, generator):
        """Test error handling for invalid style."""
        with pytest.raises(ValueError, match="Invalid styles"):
            generator.generate_portrait("Test", styles=["Invalid"])

    def test_generate_portrait_includes_metadata(self, generator):
        """Test that result includes subject metadata."""
        result = generator.generate_portrait("Test Person")

        assert result.metadata is not None
        assert result.metadata.name == "Test Person"
        assert result.metadata.birth_year > 0

    def test_generate_portrait_includes_evaluation(self, generator):
        """Test that result includes evaluation results."""
        result = generator.generate_portrait("Test Person")

        assert len(result.evaluation) > 0
        for style, eval_result in result.evaluation.items():
            assert isinstance(eval_result, EvaluationResult)

    def test_generate_portrait_tracks_time(self, generator):
        """Test that generation time is tracked."""
        result = generator.generate_portrait("Test Person")

        assert result.generation_time_seconds > 0

    def test_generate_portrait_force_regenerate(self, generator, temp_output_dir):
        """Test force regeneration overwrites existing files."""
        # Generate once
        result1 = generator.generate_portrait("Test")

        # Modify file
        file_path = Path(result1.files["BW"])
        original_size = file_path.stat().st_size
        file_path.write_text("modified")

        # Generate again with force
        result2 = generator.generate_portrait("Test", force_regenerate=True)

        # File should be regenerated
        new_size = Path(result2.files["BW"]).stat().st_size
        assert new_size != len("modified")

    def test_generate_portrait_researcher_failure(
        self, generator, mock_researcher
    ):
        """Test handling of researcher failure."""
        mock_researcher.research_subject.side_effect = Exception("Research failed")

        result = generator.generate_portrait("Test")

        assert result.success is False
        assert len(result.errors) > 0

    def test_generate_portrait_image_generation_failure(
        self, generator, mock_gemini_client
    ):
        """Test handling of image generation failure."""
        mock_gemini_client.generate_image.side_effect = Exception("API Error")

        result = generator.generate_portrait("Test")

        assert result.success is False
        assert len(result.errors) > 0


class TestGenerateVersion:
    """Tests for _generate_version private method."""

    def test_generate_version_creates_files(self, generator, temp_output_dir):
        """Test that _generate_version creates files."""
        subject_data = SubjectData(
            name="Test Person",
            birth_year=1900,
            death_year=1950,
            era="20th Century",
        )

        image_path, prompt_path = generator._generate_version(
            subject_data, "Color"
        )

        assert image_path.exists()
        assert prompt_path.exists()

    def test_generate_version_bw_transformation(
        self, generator, mock_gemini_client
    ):
        """Test that BW style applies transformation."""
        subject_data = SubjectData(
            name="Test",
            birth_year=1900,
            death_year=1950,
            era="Modern",
        )

        image_path, _ = generator._generate_version(subject_data, "BW")

        # Image should be created
        assert image_path.exists()

    def test_generate_version_sepia_transformation(self, generator):
        """Test that Sepia style applies transformation."""
        subject_data = SubjectData(
            name="Test",
            birth_year=1900,
            death_year=1950,
            era="Modern",
        )

        image_path, _ = generator._generate_version(subject_data, "Sepia")

        assert image_path.exists()

    def test_generate_version_skips_existing(self, generator, temp_output_dir):
        """Test that existing files are skipped."""
        subject_data = SubjectData(
            name="Test",
            birth_year=1900,
            death_year=1950,
            era="Modern",
        )

        # Generate once
        image_path1, _ = generator._generate_version(subject_data, "Color")
        modify_time1 = image_path1.stat().st_mtime

        # Generate again without force
        image_path2, _ = generator._generate_version(
            subject_data, "Color", force_regenerate=False
        )
        modify_time2 = image_path2.stat().st_mtime

        # Should be same file (not regenerated)
        assert modify_time1 == modify_time2


class TestCreatePrompt:
    """Tests for _create_prompt method."""

    def test_create_prompt_includes_name(self, generator):
        """Test that prompt includes subject name."""
        subject_data = SubjectData(
            name="Albert Einstein",
            birth_year=1879,
            death_year=1955,
            era="20th Century",
        )

        prompt = generator._create_prompt(subject_data, "Color")

        assert "Albert Einstein" in prompt

    def test_create_prompt_includes_era(self, generator):
        """Test that prompt includes era."""
        subject_data = SubjectData(
            name="Test",
            birth_year=1900,
            death_year=1950,
            era="Medieval",
        )

        prompt = generator._create_prompt(subject_data, "Color")

        assert "Medieval" in prompt

    def test_create_prompt_different_styles(self, generator):
        """Test that prompts differ by style."""
        subject_data = SubjectData(
            name="Test",
            birth_year=1900,
            death_year=1950,
            era="Modern",
        )

        prompt_bw = generator._create_prompt(subject_data, "BW")
        prompt_sepia = generator._create_prompt(subject_data, "Sepia")

        assert prompt_bw != prompt_sepia
        assert "black and white" in prompt_bw.lower()
        assert "sepia" in prompt_sepia.lower()

    def test_create_prompt_includes_quality_requirements(self, generator):
        """Test that prompt includes quality requirements."""
        subject_data = SubjectData(
            name="Test",
            birth_year=1900,
            death_year=1950,
            era="Modern",
        )

        prompt = generator._create_prompt(subject_data, "Color")

        assert "quality" in prompt.lower() or "publication" in prompt.lower()


class TestGetStyleInstructions:
    """Tests for _get_style_instructions method."""

    def test_get_style_instructions_bw(self, generator):
        """Test BW style instructions."""
        instructions = generator._get_style_instructions("BW")

        assert "black and white" in instructions.lower()

    def test_get_style_instructions_sepia(self, generator):
        """Test Sepia style instructions."""
        instructions = generator._get_style_instructions("Sepia")

        assert "sepia" in instructions.lower()

    def test_get_style_instructions_color(self, generator):
        """Test Color style instructions."""
        instructions = generator._get_style_instructions("Color")

        assert "color" in instructions.lower()

    def test_get_style_instructions_painting(self, generator):
        """Test Painting style instructions."""
        instructions = generator._get_style_instructions("Painting")

        assert "painting" in instructions.lower()

    def test_get_style_instructions_unknown(self, generator):
        """Test unknown style returns default."""
        instructions = generator._get_style_instructions("Unknown")

        assert len(instructions) > 0


class TestApplyStyleTransformation:
    """Tests for _apply_style_transformation method."""

    def test_apply_style_transformation_bw(self, generator):
        """Test BW transformation."""
        image = Image.new("RGB", (100, 100), color=(255, 0, 0))

        result = generator._apply_style_transformation(image, "BW")

        # Check that result is grayscale
        pixels = list(result.getdata())
        r, g, b = pixels[0]
        assert r == g == b

    def test_apply_style_transformation_sepia(self, generator):
        """Test Sepia transformation."""
        image = Image.new("RGB", (100, 100), color=(255, 0, 0))

        result = generator._apply_style_transformation(image, "Sepia")

        # Check that result has warm tones
        pixels = list(result.getdata())
        r, g, b = pixels[0]
        assert r >= g >= b

    def test_apply_style_transformation_color(self, generator):
        """Test Color transformation (no change)."""
        image = Image.new("RGB", (100, 100), color=(255, 0, 0))

        result = generator._apply_style_transformation(image, "Color")

        # Should be unchanged
        assert result.getpixel((0, 0)) == (255, 0, 0)

    def test_apply_style_transformation_painting(self, generator):
        """Test Painting transformation (no change)."""
        image = Image.new("RGB", (100, 100), color=(255, 0, 0))

        result = generator._apply_style_transformation(image, "Painting")

        # Should be unchanged
        assert result.getpixel((0, 0)) == (255, 0, 0)


class TestCreateFilename:
    """Tests for _create_filename method."""

    def test_create_filename_simple(self, generator):
        """Test filename creation for simple name."""
        filename = generator._create_filename("Albert Einstein", "BW")

        assert filename == "AlbertEinstein_BW"

    def test_create_filename_removes_spaces(self, generator):
        """Test that spaces are removed."""
        filename = generator._create_filename("John von Neumann", "Color")

        assert " " not in filename

    def test_create_filename_capitalizes(self, generator):
        """Test that name parts are capitalized."""
        filename = generator._create_filename("alan turing", "Sepia")

        assert "Alan" in filename
        assert "Turing" in filename

    def test_create_filename_different_styles(self, generator):
        """Test filename differs by style."""
        filename_bw = generator._create_filename("Test", "BW")
        filename_color = generator._create_filename("Test", "Color")

        assert filename_bw != filename_color
        assert "_BW" in filename_bw
        assert "_Color" in filename_color

    def test_create_filename_removes_special_chars(self, generator):
        """Test that special characters are removed."""
        filename = generator._create_filename("Name (test) [2024]", "BW")

        assert "(" not in filename
        assert "[" not in filename


class TestCheckExistingPortraits:
    """Tests for check_existing_portraits method."""

    def test_check_existing_portraits_none_exist(self, generator):
        """Test checking when no portraits exist."""
        results = generator.check_existing_portraits("Nonexistent Person")

        assert all(not exists for exists in results.values())

    def test_check_existing_portraits_some_exist(self, generator, temp_output_dir):
        """Test checking when some portraits exist."""
        # Generate one style
        generator.generate_portrait("Test", styles=["BW"])

        # Check
        results = generator.check_existing_portraits("Test")

        assert results["BW"] is True
        assert results["Color"] is False

    def test_check_existing_portraits_all_exist(self, generator):
        """Test checking when all portraits exist."""
        # Generate all styles
        generator.generate_portrait("Test")

        # Check
        results = generator.check_existing_portraits("Test")

        assert all(exists for exists in results.values())


class TestGenerateBatch:
    """Tests for generate_batch method."""

    def test_generate_batch_success(self, generator):
        """Test successful batch generation."""
        names = ["Person 1", "Person 2", "Person 3"]

        results = generator.generate_batch(names)

        assert len(results) == 3
        assert all(isinstance(r, PortraitResult) for r in results)

    def test_generate_batch_empty_list(self, generator):
        """Test error handling for empty list."""
        with pytest.raises(ValueError, match="cannot be empty"):
            generator.generate_batch([])

    def test_generate_batch_with_styles(self, generator):
        """Test batch generation with specific styles."""
        names = ["Person 1", "Person 2"]

        results = generator.generate_batch(names, styles=["BW", "Color"])

        assert len(results) == 2
        for result in results:
            assert len(result.files) == 2

    def test_generate_batch_handles_failures(self, generator, mock_researcher):
        """Test that batch continues after individual failures."""
        mock_researcher.research_subject.side_effect = [
            SubjectData(
                name="Person 1",
                birth_year=1900,
                death_year=1950,
                era="Modern",
            ),
            Exception("Research failed"),
            SubjectData(
                name="Person 3",
                birth_year=1900,
                death_year=1950,
                era="Modern",
            ),
        ]

        names = ["Person 1", "Person 2", "Person 3"]
        results = generator.generate_batch(names)

        assert len(results) == 3
        assert results[0].success is True
        assert results[1].success is False
        assert results[2].success is True


class TestIntegration:
    """Integration tests for PortraitGenerator."""

    def test_full_generation_workflow(self, generator, temp_output_dir):
        """Test complete generation workflow."""
        result = generator.generate_portrait("Test Person")

        # Check success
        assert result.success is True

        # Check files created
        assert len(result.files) == 4
        for file_path in result.files.values():
            path = Path(file_path)
            assert path.exists()
            assert path.stat().st_size > 0

        # Check prompts created
        assert len(result.prompts) == 4
        for prompt_path in result.prompts.values():
            path = Path(prompt_path)
            assert path.exists()
            content = path.read_text()
            assert len(content) > 100

        # Check evaluations
        assert len(result.evaluation) == 4
        for eval_result in result.evaluation.values():
            assert isinstance(eval_result, EvaluationResult)

        # Check metadata
        assert result.metadata.name == "Test Person"

    def test_workflow_uses_all_components(
        self,
        generator,
        mock_researcher,
        mock_gemini_client,
        mock_overlay_engine,
        mock_evaluator,
    ):
        """Test that workflow uses all components."""
        generator.generate_portrait("Test")

        # Verify all components were called
        mock_researcher.research_subject.assert_called()
        mock_gemini_client.generate_image.assert_called()
        mock_overlay_engine.add_overlay.assert_called()
        mock_evaluator.evaluate_portrait.assert_called()

    def test_workflow_creates_correct_file_structure(
        self, generator, temp_output_dir
    ):
        """Test that correct file structure is created."""
        generator.generate_portrait("Albert Einstein")

        # Check expected files exist
        expected_files = [
            "AlbertEinstein_BW.png",
            "AlbertEinstein_BW_prompt.md",
            "AlbertEinstein_Sepia.png",
            "AlbertEinstein_Sepia_prompt.md",
            "AlbertEinstein_Color.png",
            "AlbertEinstein_Color_prompt.md",
            "AlbertEinstein_Painting.png",
            "AlbertEinstein_Painting_prompt.md",
        ]

        for filename in expected_files:
            file_path = temp_output_dir / filename
            assert file_path.exists(), f"Missing file: {filename}"
