{% set name = "portrait-generator" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/davidlary/PortraitGenerator/archive/v{{ version }}.tar.gz
  sha256: 2fa42826d6e0d8d1643842841e95b719d026e47f887c6069e4db2d623ab8f663

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - portrait-generator = portrait_generator.cli:main
    - portrait-gen = portrait_generator.cli:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >=3.10
    - google-genai >=1.0.0,<2.0.0
    - pillow >=11.0.0,<12.0.0
    - fastapi >=0.100.0,<1.0.0
    - uvicorn >=0.27.0,<1.0.0
    - pydantic >=2.6.0,<3.0.0
    - pydantic-settings >=2.1.0,<3.0.0
    - click >=8.0.0,<9.0.0
    - httpx >=0.26.0,<1.0.0
    - requests >=2.31.0,<3.0.0
    - python-dotenv >=1.0.0,<2.0.0
    - loguru >=0.7.0,<1.0.0

test:
  imports:
    - portrait_generator
    - portrait_generator.api
    - portrait_generator.core
    - portrait_generator.utils
    - portrait_generator.config
    - portrait_generator.client
    - portrait_generator.cli
  commands:
    - portrait-generator --version
    - portrait-generator --help
    - portrait-gen --version

about:
  home: https://github.com/davidlary/PortraitGenerator
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: AI-powered historical portrait generation using Google Gemini 3 Pro Image
  description: |
    Portrait Generator v2.0.0 creates historically accurate portraits using
    Google's Gemini 3 Pro Image (Nano Banana Pro) with advanced AI features.

    NEW in 2.0.0:
    - Google Search grounding for real-time fact-checking
    - Multi-image references (up to 14 authentic historical images)
    - Internal reasoning and iterative refinement
    - Physics-aware synthesis for realistic lighting and materials
    - Pre-generation validation with proactive error detection
    - Smart retry with autonomous prompt refinement
    - Holistic AI evaluation with multi-pass reasoning
    - 85%+ first-attempt success rate

    Core Features:
    - 4 portrait styles: BW, Sepia, Color, Painting
    - REST API with FastAPI
    - Python API for programmatic use
    - Command-line interface
    - 370+ tests with comprehensive coverage

  doc_url: https://portrait-generator.readthedocs.io
  dev_url: https://github.com/davidlary/PortraitGenerator

extra:
  recipe-maintainers:
    - davidlary
